### ISSUE TITLE
[OLD] Legacy Traditional Chinese Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/zh-hant.react.dev#1]
## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@itszero) #6 
* [x] Tutorial (@chloewlin) #9 

### Basics

* [x] Hello World (@JuanitoFatas) #4 
* [x] Introducing JSX (@itszero) #13
* [x] Rendering Elements (@neighborhood999) #11 
* [x] Components and Props (@bugtender) #12 
* [x] State and Lifecycle (@neighborhood999) #16
* [x] Handling Events (@chloewlin) #74 
* [x] Conditional Rendering (@ivan-ha) #18
* [x] Lists and Keys (@chloewlin) #17
* [x] Forms (@chloewlin) #59 
* [x] Lifting State Up (@neighborhood999) #33 
* [x] Composition vs Inheritance (@neighborhood999) #39 
* [x] Thinking in React (@chloewlin) #20

### API Reference

* [x] React (@itszero) #28 
* [x] React.Component (@chloewlin) #75 
* [x] ReactDOM (@abrcdf1023) #38 
* [x] ReactDOMServer (@chloewlin) #80 
* [x] DOM Elements (@piovischioh) #40 
* [x] SyntheticEvent (@chloewlin) #81
* [x] Test Utilities (@vrabe) #56 
* [x] Shallow Renderer (@barrypeng6) #42 
* [x] Test Renderer (@barrypeng6) #43 
* [x] JS Environment Requirements (@ivan-ha) #37
* [x] Glossary (@ivan-ha) #36

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@chloewlin) #78 
* [x] docs/nav.yml (@neighborhood999) #70

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@fabianlee1211) #41 
* [x] Add React to a Website (@fabianlee1211) #45
* [x] Create a New React App (@fabianlee1211) #52 
* [x] CDN Links (@fabianlee1211) #50

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@chentsulin) #34 
  * [x] Hooks at a Glance (@BruceWeng) #35
  * [x] Using the State Hook (@piovischioh) #67
  * [x] Using the Effect Hook (@leah-z-liu) #103 
  * [x] Rules of Hooks (@KevinHu2014) #63
  * [x] Building Your Own Hooks (@neighborhood999) #72 
  * [x] Hooks API Reference (@ivan-ha) #69 
  * [x] Hooks FAQ (@neighborhood999) #97 

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop (@neighborhood999)

### Advanced Guides

* [x] Accessibility (@chloewlin) #112
* [x] Code-Splitting (@neighborhood999) #55 
* [ ] Context (@chloewlin)
* [x] Error Boundaries (eyeccc) #104 
* [x] Forwarding Refs (eyeccc) #118 
* [x] Fragments (@RickyWooo) #94 
* [ ] Higher-Order Components (@yikkok-yong)
* [ ] Integrating with Other Libraries
* [x] JSX In Depth (@aboudicheng) #102 
* [ ] Optimizing Performance (@chloewlin)
* [x] Portals (@henry61024) #199 
* [ ] Profiler (@henry61024)
* [x] React Without ES6 (@henry61024) #203 
* [x] React Without JSX (@yunkii) #122 
* [x] Reconciliation (@HcwXd) #95 
* [x] Refs and the DOM (@eyeccc) #120
* [x] Render Props (@huantingwei) #176
* [ ] Static Type Checking (@vrabe)
* [x] Strict Mode (@eyeccc) #105 
* [ ] Typechecking With PropTypes (@yunkii)
* [x] Uncontrolled Components (@eyeccc) #106 
* [x] Web Components (@eyeccc) #107  

### FAQ

* [x] APIs and AJAX (@JuanitoFatas) #3 
* [x] Babel, JSX, and Build Steps (@lithiumpie) #160 
* [ ] Passing Functions to Components
* [x] Component State (@lithiumpie) #162
* [x] Styling and CSS (@huantingwei) #201 
* [x] File Structure (@huantingwei) #204 
* [ ] Versioning Policy 
* [ ] Virtual DOM and Internals

### Testing

* [x] Testing Overview (@neighborhood999) #148 
* [ ] Testing Recipes
* [x] Testing Environments (@neighborhood999) #149 

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by itszero** [comment]
I'd love to help! Maybe I can try by taking the Home page first? 

I'm slightly confused about the process though. Should we be working on Crowdin or work off this repo and submit a PR instead?

Thanks! :smile:

**Comment by tesseralis** [comment]
@itszero you should work off this repo and submit a PR. You can copy-paste from crowdin if you find that a useful start to your translations!

**Comment by tesseralis** [comment]
@itszero I gave you the home page!

**Comment by chloewlin** [comment]
Hi @itszero, there are currently five maintainers for this version. Some people are in Taiwan and are on vacation. We will also discuss how to coordinate with everyone else soon!

**Comment by itszero** [comment]
Got it. I also got your email, will discuss it further offline with you. Thanks for coordinating.

**Comment by chloewlin** [comment]
Hi @chentsulin, @neighborhood999, @bugtender, @itszero, and @haimengzhang, welcome to the team! 

I know half of you are still on vacation, but it's about time for us to get started! @itszero is already working on homepage. Everyone, please look at the content and claim what you'd like to work on. :) 

A few thoughts: 

1. **Standardization of Glossary**: I want to bring your attention to chentsu's complete [Redux translation](https://chentsulin.github.io/redux/index.html) and a popular React [handbook](https://github.com/kdchang/reactjs101) that have served the function of an official doc. Both translations are great! I suggest we use them as references to **standardize technical glossary** to ensure that all the technical terms are **consistent across the entire documentation**.  Why? Two reasons: (1) Our translation will set up the standard for how people understand or talk about React in the Chinese speaking world, since there are no official docs for React yet. (2) Contributors and reviewers might have different opinions on how one thing should be translated. It will be more efficient to agree on these terms first.

    Examples of ambiguities we should discuss: 

    - [ ] Should `Component` be `元件`, `組件`,  `元素` ? Will there be collisions? 
    - [ ] Should we keep `render` as render in English or translate it as `渲染` or `描繪` ? (See 
    Simplified Chinese for [reference](https://react.docschina.org/docs/rendering-elements.html)) As @itszero pointed out, `渲染` is often used in [3D modeling](https://zh.wikipedia.org/wiki/%E6%B8%B2%E6%9F%93). We could even consider keeping react-specific methods like `render` and `componentDidMount` as they are in English.

    For ambiguities like these, we can set up a quick one hour conference call to reach a consensus on the glossary before we head out to work on our part of the translation. 

2.  **Standardization of Style**: Most of open source contributors follow this [Chinese copywriting guidelines](https://github.com/sparanoid/chinese-copywriting-guidelines). Nat created a [universal guide](https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md). We should follow them.

3. **Transparency of Discussion**: To facilitate discussion between contributors and reviewers, we could consider communicating over Twitter or other platforms. But we should always keep github as the source of truth and keep our great @tesseralis updated with our progress. 

Feel free to provide other sample translations we can use as references. Any thoughts on how we can improve the process are much appreciated. Again, welcome to the team!

**Comment by neighborhood999** [comment]
I prefer to keep some tech terms as the original. As @chloewlin mentioned above:

In the Traditional Chinese, `Component` can translate `元件` or `組件`, but in some technical term like “Higher Order Component”, maybe we can translate to “高階元件（組件）”, but for the beginners they are maybe not familiar with this technical term, so I think to keep the original term can let beginners recognize common technical terms. In the most (English) article, people will see the “Higher Order Component” not the “高階元件（組件）”.

Maybe we can create a list of glossary for the Traditional Chinese, list common terms and describe the terms should be translated or not.

**Comment by bugtender** [comment]
Hi, everyone. 
I have read chentsu's Redux book when I learn Redux before. And I agree it's a good reference for us. As @neighborhood999 said, maybe we can create the first glossary base on the [glossary from this book](http://chentsulin.github.io/redux/docs/Glossary.html).

**Comment by bugtender** [comment]
Oh, and I'll take the Tutorial's part. 😂 Happy Lunar New Year 🧨

**Comment by JuanitoFatas** [comment]
I could take the Basics section 🙋

**Comment by chloewlin** [comment]
Awesome. I want to quote how @chentsulin translates reducer: 

> reducer (也稱作 reducing function) 是一個 function，它接收累積值和一個值並回傳新的累積值。它們通常被用來把一組值 reduce down 成一個單一值。

Notice how he uses English for 'reducer', 'function', and even 'reduce down'.

> Reducer 不是 Redux 獨有的—它們是 functional programming 裡的基礎概念。甚至大多數的非 functional language，像是 JavaScript，都有一個內建的 reducing API。在 JavaScript 裡，那就是 Array.prototype.reduce()。

Notice how 'functional programming' is in English.

> 在 Redux 裡，累積值就是 state 物件，而被累積的值就是 action。Reducer 依照先前的 state 和一個 action 來計算一個新的 state。它們必須是 pure function—就是對給定的 input 每次會回傳完全一樣的 output 的 function。它們也應該是沒有 side-effect 的。這就是使像是 hot reload 和 time travel 等令人興奮的功能成真的東西。

Notice how 'pure function', 'input', 'output', and even 'side-effect' are all in English.

Given that we all code in English, sometimes it's better to mix English with Chinese, rather than coming up with awkward translations that no one really uses. Can we all agree on this? 

@JuanitoFatas welcome to the team! We're deciding on translation style now, and will set up an initial conference call or a platform for everyone. Please join us!

**Comment by JuanitoFatas** [comment]
> Given that we all code in English, sometimes it's better to mix English with Chinese, rather than coming up with awkward translations that no one really uses. Can we all agree on this?

Sounds good to me.

> We're deciding on translation style now, and will set up an initial conference call or a platform for everyone. Please join us!

Could we try a way (issue or wiki) to discuss these terms that in asynchronous fashion?  People have different time and priorities, may be hard to schedule a meeting time that works for all of us.

**Comment by chloewlin** [comment]
> Could we try a way (issue or wiki) to discuss these terms that in asynchronous fashion? People have different time and priorities, may be hard to schedule a meeting time that works for all of us.

@JuanitoFatas Most of our members are either in SF or Taipei. We want to do just **one** initial phone call to quickly go through some issues like style and process and make sure that everyone is on the same page. I think it's not hard since Tokyo is in almost the same time zone as Taipei. But if you are too busy to join, it's fine. We will definitely set up a platform to facilitate discussion too.

**Comment by chloewlin** [comment]
@itszero @neighborhood999 @chentsulin @bugtender @haimengzhang @JuanitoFatas Now that our team is growing, it is indeed getting harder to coordinate with everyone's time. Do we still want an initial call (<30 mins)? If not that's fine too. We can set up **Slack, Spectrum, Twitter, or Telegram**. NO Line because @itszero doesn't have Line. lol Please voice your preference!

**Comment by itszero** [comment]
Nice to see everyone online now. :smile: If we'd like to keep the conversation more open and accessible: Spectrum is a good idea. Otherwise, I'm on all the other three platforms (preference wise: Telegram > Twitter > Slack).

Totally agree on keeping some words in English -- as for the extent, we can discuss that later. I think the last example in @chloewlin's reply feels a bit too fragmented.

I'll try to give the home page a first-pass tomorrow. Looking forward to work with y'all!

**Comment by haimengzhang** [comment]
Hi everyone,

Nice to work with you all.

With communication channels,  I'd prefer Slack or Twitter, but I will go
with what most people prefer.

Just a note, I'm also translating in Simplified Chinese at the mean time,
and "component" is tranlated to 组件,  shall we keep it consistent?

In general, do we want to keep the vocabs consistent with the Simplified
Chinese team?

Haimeng

**Comment by itszero** [comment]
_Personal Opinion_ I think the target audience of having Traditional Chinese translation is mostly for Taiwanese users. Therefore, we should strive for localizing it for those users too. I don't think people will cross-reference SC/TC documents so keeping that consistent doesn't make much more sense than making it easier to read to our target audience.  We also briefly chatted about the possibility of keeping more terms in its English form above.

**Comment by chloewlin** [comment]
Hey @haimengzhang! So I agree with @itszero. Personally, the reason why I want to work on Traditional Chinese is because I find it very difficult to understand the way React is translated in Simplified Chinese. I would not use `组件` or `渲染` because that is not how people who don't use Simplified Chinese would use. It would be pointless to keep them consistent since they are by nature two very distinct languages with different vocabulary and syntax. In other words, we're no just changing characters. We want to create high-quality, natural, accurate translations for readers in Traditional Chinese. And FYI, `组件` sounds like lego to me.

**Comment by haimengzhang** [comment]
Ok, sounds good to me! :)

**Comment by chloewlin** [comment]
I updated the list from the top. I will work on translating the tutorial.

**Comment by itszero** [comment]
I'll also take another one: Introducing JSX.

**Comment by neighborhood999** [comment]
@itszero I update the list on the above, assign *Introducing JSX* for you, thank you.

By the way, I take the *Rendering Elements*.

**Comment by ivan-ha** [comment]
Hello there, React dev from from Hong Kong and love to help!

Maybe I could take _Conditional Rendering_?

**Comment by chentsulin** [comment]
I will take Hooks part if no one works on it.

**Comment by chloewlin** [comment]
@ivan-ha I will update your name on _conditional rendering_. Remember to read the glossary page in Wiki and follow the style guide. Welcome.

@chentsulin No problem! I am also interested in that, but I am still working on tutorials now. Let me know if you need extra help. :)

**Comment by haimengzhang** [comment]
I'll claim Handling Events if no one is.

**Comment by chloewlin** [comment]
@haimengzhang no problem! I updated your name in our list on the top. :)

**Comment by chloewlin** [comment]
I completed the tutorial. It's under review right now. 

I am going to work on (1) lists and keys and (2) forms next if no one is working on it. Thanks!

**Comment by chloewlin** [comment]
The rest of the articles in **Basics** are all claimed! Anyone who wants to charge ahead, please move on to **API References** and other sections.

**Comment by ivan-ha** [comment]
Hi, is there a consense how we translate words inside code block?
https://github.com/reactjs/reactjs.org-translation/blob/master/style-guide.md#text-in-code-blocks

in this example
```js
// Example
const element = <h1>Hello, world</h1>;
ReactDOM.render(element, document.getElementById('root'));
```

should we do this?
```js
// 例子
const element = <h1>Hello, world</h1>;
ReactDOM.render(element, document.getElementById('root'));
```

or this?
```js
// 例子
const element = <h1>你好，世界</h1>;
ReactDOM.render(element, document.getElementById('root'));
```

**Comment by tesseralis** [comment]
It’s up to the translation team—just make sure it’s consistent.

**Comment by chloewlin** [comment]
@ivan-ha we will go with this: translate the comments, but leave everything else alone. I will review your PR soon!

> ```js
> // 例子
> const element = <h1>Hello, world</h1>;
> ReactDOM.render(element, document.getElementById('root'));
> ```

**Comment by itszero** [comment]
I'll take the API / React!

**Comment by dennisgl** [comment]
Hi all, I will love to hop on the train! 🚄 **I can take on `docs/events.html`(API/SyntheticEvent) as a starter.**

@chloewlin if any, can you please send me the details of communication channels and coordination plans via email?

**Comment by chloewlin** [comment]
@dennisgl I received your LinkedIn invite. I can update you from there. For now, please take a look at our completed translations so far and the wiki page to understand our style.

**Comment by chloewlin** [comment]
@dennisgl I give you SyntheticEvent!

**Comment by abrcdf1023** [comment]
@chloewlin HI, I want to take ReactDOM as the first shot can I try it?

**Comment by chloewlin** [comment]
Hey @abrcdf1023 Yes, go ahead and try it. I've added your handle to the top post. Please make sure you read (1) some of our merged translations, (2) the wiki page, and (3) [this guideline](https://github.com/sparanoid/chinese-copywriting-guidelines) to understand our style. We're also working on updating the documents on (1) the glossary and (2) community policy/work flow. Welcome!

**Comment by BruceWeng** [comment]
Hi @chloewlin could you label PR doc: Translate Hooks #32 as In Progress?
I am working on it. Thanks!

**Comment by chloewlin** [comment]
Hi @BruceWeng welcome. So @chentsulin actually claimed to work on hooks earlier, too. If you look at the top post, you will notice that his account is already here. I am not sure if he is still interested. I will double check with him first.

**Comment by BruceWeng** [comment]
That's ok. I am half way finish Introducing Hooks. Gonna push the commit tomorrow. Since there are several articles about hooks, but no progress now, I will translate one topic per day in the same PR. Free to modify anytime. 😄

**Comment by ivan-ha** [comment]
Finish with conditional rendering, I could take [Glossary](https://reactjs.org/docs/glossary.html). Maybe with [JavaScript Environment Requirements](https://reactjs.org/docs/javascript-environment-requirements.html) also, that one is really short.

**Comment by BruceWeng** [comment]
Head up that I am working on Hooks at a Glance, expect to finish tomorrow. It would be nice if @chloewlin can label the ownership for me~

**Comment by BruceWeng** [comment]
Finish with Hooks at a Glance here #35. Please review it if anyone has time~

**Comment by piovischioh** [comment]
Hi @chloewlin, I could help to translate [DOM Elements](https://reactjs.org/docs/dom-elements.html).

**Comment by chloewlin** [comment]
Hi @piovischioh I give it to you! Make sure to (1) read some of the translations so far, (2) read glossary in wiki. Let me know whenever you have any questions! :)

**Comment by abrcdf1023** [comment]
@chloewlin I want to do next! May I take the ReactDOMServer?

**Comment by chloewlin** [comment]
@abrcdf1023 yes! I just assigned it to you.

**Comment by vrabe** [comment]
Hello, @chloewlin . Could I take Test Utilities?

**Comment by fabianlee1211** [comment]
@chloewlin Hello there! Can I take the Getting Started section please?

**Comment by barrypeng6** [comment]
Hello @chloewlin I could take **Shallow Renderer** section.

**Comment by chloewlin** [comment]
@vrabe  @fabianlee1211 @barrypeng6 welcome! Please (1) read some of the translations we have merged in and (2) check out **glossary** in wiki that the community has agreed to keep in English. (3) Open a PR once you have started your translation. Find me on Twitter if you have any questions!

**Comment by piovischioh** [comment]
I could take **Using the State Hook** for the next.

**Comment by barrypeng6** [comment]
Hi, @chloewlin I also take **Test Renderer**. Thx.

**Comment by chloewlin** [comment]
@piovischioh @barrypeng6 no problem! The top list has been updated.

**Comment by BruceWeng** [comment]
@chloewlin Hooks at a Glance was merged.
I will take Using the Effect Hook next. Please help me to update the list for ownership. Thanks!

**Comment by bugtender** [comment]
@BruceWeng No problem, I updated it. 👍

**Comment by fabianlee1211** [comment]
@chloewlin I would like to move on to Add React to a Website please!

**Comment by neighborhood999** [comment]
Hi @fabianlee1211, No problem! I updated the list.

**Comment by chloewlin** [comment]
> I'll claim Handling Events if no one is.

Hey @haimengzhang how are you doing on this translation? If you are too busy to do it, let me know so that I can take over.

**Comment by fabianlee1211** [comment]
@chloewlin it's me again :raised_hand: I'll take the remaining parts for Installation if that's ok.

**Comment by neighborhood999** [comment]
@fabianlee1211 I updated the list, thank you.

**Comment by dolphinlin** [comment]
In my opinion, `UI` is more clear and better than `使用者介面`.

**Comment by chloewlin** [comment]
Hey @haimengzhang, it's been a while since we hear from you last time. I am going to translate `Handling Events` so that we can complete the `Basics` section this weekend. Sorry! Please feel free to work on other translations when you have time. 🙂

**Comment by KevinHu2014** [comment]
Hi @chloewlin 
Can I take `Rules of Hooks` please?

**Comment by chloewlin** [comment]
Hi @KevinHu2014, yes, I've assigned it to you. Please read the community guidelines and open a PR for it. Welcome!

**Comment by ivan-ha** [comment]
@chloewlin me again, would like to take `Hooks API Reference` 🙋‍♂

**Comment by chloewlin** [comment]
hey @ivan-ha good to see you again! Here you go. Looking forward to seeing your PR.

**Comment by neighborhood999** [comment]
I take the `Building Your Own Hooks`.

**Comment by chloewlin** [comment]
Hey everyone, we only have 26% left to be done. For those who have claimed some articles but haven't set up a PR, can you confirm that you are still interested/available to finish your translation? 
-  ReactDOMServer (@abrcdf1023)
-  SyntheticEvent (@dennisgl)
-  Using the Effect Hook (@BruceWeng)

Also, if you don't have time to finish what you are working on, you can still push your draft up and let someone else pick it up. If your article is too long, feel free to split up sections and let me help you.

**Comment by BruceWeng** [comment]
@chloewlin I might not have time working on Using the Effect Hook recently. Free to release it to the community!

**Comment by leah-z-liu** [comment]
Hey @chloewlin I'd love to help! Can I take Using the Effect Hook?

**Comment by chloewlin** [comment]
Hey @leah-z-liu, yes, you can take it if you are comfortable translating in Traditional Chinese. Please take a look at our wiki and the already translated Hook articles for reference. Welcome. :)

**Comment by chloewlin** [comment]
Hey @abrcdf1023 and @dennisgl, I haven't heard back from y'all for a while, so I had to update the list so that others can take them over. If you're still interested in helping, please ping me or contribute to other articles in this list. :) 

For other contributors: if you can, prioritize a **core** page. Let's meet the 100% core page first before we charge ahead!

**Comment by RickyWooo** [comment]
Hi @chloewlin , looks like both ReactDOMServer & SyntheticEvent chapter have been translated, may I take Fragments and make a little contribution? thanks :)

**Comment by chloewlin** [comment]
@RickyWooo of course! I put your name down already.

**Comment by chloewlin** [comment]
Hi @leah-z-liu! Have you finished your work on the Effect Hook? :) The community is really looking forward to completing the translation regarding Hooks soon. Let me know where you're at.

**Comment by yikkok-yong** [comment]
Hi @chloewlin, I would like to contribute translating the `Higher Order Component`.

**Comment by leah-z-liu** [comment]
> Hi @leah-z-liu! Have you finished your work on the Effect Hook? :) The community is really looking forward to completing the translation regarding Hooks soon. Let me know where you're at.

Hey @chloewlin the translation is about 80% done. I'll submit PR this weekend :)

**Comment by chloewlin** [comment]
Hi @yikkok-yong, welcome! It's yours. Hey @leah-z-liu, thanks for your update. I look forward to reviewing it. :)

**Comment by aboudicheng** [comment]
Hi @chloewlin! I'd like to take `JSX In Depth` if that's okay with you. Thanks!

**Comment by chloewlin** [comment]
Hey @aboudicheng it's yours! Just open a PR when you're done. Welcome!

**Comment by eyeccc** [comment]
Hi @chloewlin 
I'd like to take `Error Boundary`. Thanks.

**Comment by BruceWeng** [comment]
Will we have a plan to translate fresh released `Concurrent Mode (Experimental)`?

**Comment by chloewlin** [comment]
@eyeccc Welcome! Thanks for opening the PRs as well. @BruceWeng that's a good question, I think we should focus on finishing the rest of the articles here, but I can double check with the React team. :) 

I am in the middle of some work now but will review the incoming PRs by @leah-z-liu and @aboudicheng soon. :)

**Comment by chloewlin** [comment]
I am taking Accessibility (#112) and Context in Advanced Guides.

**Comment by eyeccc** [comment]
Hey @chloewlin 
I'll take `Forwarding Refs` (#118). 
Thanks

**Comment by neighborhood999** [comment]
Hi @eyeccc, thank you for helping!

I updated the list.

**Comment by eyeccc** [comment]
hi @chloewlin 
i'll take one more translation: `Refs and the DOM` (#120) :)

**Comment by chloewlin** [comment]
@eyeccc thanks for tagging me! I updated the list for you. It's Christmas here so I've been a little slow in response. I look forward to your PR. :)

**Comment by yunkii** [comment]
Hi all, 👋 
I'm taking the react without jsx. #122 :)

**Comment by neighborhood999** [comment]
Hi @yunkii, thank you for helping! I'm updated the list for you.

**Comment by neighborhood999** [comment]
I will take `Testing Overview`.

**Comment by neighborhood999** [comment]
I'll take `Testing Environments`.

**Comment by lithiumpie** [comment]
@neighborhood999 hi, I'm going to take `faq-build`

**Comment by neighborhood999** [comment]
@lithiumpie Thank you for your help!

**Comment by lithiumpie** [comment]
Hey~ @neighborhood999 I take faq-state

**Comment by neighborhood999** [comment]
> Hey~ @neighborhood999 I take faq-state

I updated list, thank you for help!

**Comment by huantingwei** [comment]
Hi, I wonder if the translation is still in progress?
If so, I would like to take  `Render Props` under `Advanced Guides`. Thanks!

**Comment by chloewlin** [comment]
Hey @huantingwei yes it is! I'll add your handle to the list. Go for it. Feel free to ping me or @neighborhood999 for PR reviews.

**Comment by vrabe** [comment]
Hello, I want to take `Static Type Checking`.

**Comment by chloewlin** [comment]
Hi @vrabe, it's yours! As always, please open a PR so that we can track your progress and review your contribution at the end. Let me know if you have any questions.

**Comment by henry61024** [comment]
Hi, I'd like to translate the article: `Portal`. Is it available?

Thanks!

**Comment by bugtender** [comment]
Hi, @henry61024 yes! Thanks for helping. I'll update the list. 👍

**Comment by huantingwei** [comment]
Hello, may I take `FAQ: File Structure` and `FAQ: Styling and CSS`?

**Comment by chloewlin** [comment]
@huantingwei yes, and welcome! I will update the list. Please feel free to ping me, @bugtender or @neighborhood999 for reviews :)

**Comment by henry61024** [comment]
Hi, I would like to work on `React Without ES6` and `Profiler` too, but it seems that `Profiler` is not on the list, is it still available?

**Comment by neighborhood999** [comment]
@henry61024 Thanks for helping. You're right, seems `Profiler` missing, I also update the list and assign `React Without ES6` and `Profiler` for you.

**Comment by neighborhood999** [comment]
I take the `unknown-prop`.

**Comment by rudy0628** [comment]
I take the `special-props`

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
Started a new issue for the new website: https://github.com/reactjs/zh-hant.react.dev/issues/260
